{% set name = "karateclub" %}
{% set version = "1.0.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 79afbd5b9eceee0f5a9d106ae3f77326d198c960ae82e2a0dfb378c690f9758f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pytest-runner
    - pip
    - python
  run:
    - gensim
    - networkx
    - numpy
    - pandas
    - pygsp
    - python
    - python-louvain
    - scikit-learn
    - scipy
    - six
    - tqdm

test:
  imports:
    - karateclub
    - karateclub.community_detection
    - karateclub.community_detection.non_overlapping
    - karateclub.community_detection.overlapping
    - karateclub.dataset
    - karateclub.graph_embedding
    - karateclub.node_embedding
    - karateclub.node_embedding.attributed
    - karateclub.node_embedding.meta
    - karateclub.node_embedding.neighbourhood
    - karateclub.node_embedding.structural
    - karateclub.utils

about:
  home: https://github.com/benedekrozemberczki/karateclub
  license: GPL-3.0-only
  license_file: LICENSE
  summary: A general purpose library for community detection, network embedding, and graph mining research.
  doc_url: https://karateclub.readthedocs.io/en/latest/index.html
  dev_url: https://github.com/benedekrozemberczki/karateclub

extra:
  recipe-maintainers:
    - cyprienc
